// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import ChatroomSelectionController from "./chatroom_selection_controller"
application.register("chatroom-selection", ChatroomSelectionController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MostSimilarController from "./most_similar_controller"
application.register("most-similar", MostSimilarController)

import NavbarDropdownController from "./navbar_dropdown_controller"
application.register("navbar-dropdown", NavbarDropdownController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
